#############################################################################
# Makefile for building: QwtExample
# Generated by qmake (2.01a) (Qt 4.8.6) on: Sun Mar 20 19:46:26 2016
# Project:  QwtExample.pro
# Template: app
# Command: /usr/lib/arm-linux-gnueabihf/qt4/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile QwtExample.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I/usr/local/qwt-6.1.2/include -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/arm-linux-gnueabihf -lm -L/usr/local/qwt-6.1.2/lib -lqwt -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/arm-linux-gnueabihf/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		window.cpp \
		gpio-sysfs.cpp \
		gz_clk.cpp \
		bcm2835.c \
		adcreader.cpp \
		iir/Bessel.cpp \
		iir/Biquad.cpp \
		iir/Butterworth.cpp \
		iir/Cascade.cpp \
		iir/ChebyshevI.cpp \
		iir/ChebyshevII.cpp \
		iir/Custom.cpp \
		iir/Elliptic.cpp \
		iir/Legendre.cpp \
		iir/PoleFilter.cpp \
		iir/RBJ.cpp \
		iir/RootFinder.cpp \
		iir/State.cpp moc_window.cpp
OBJECTS       = main.o \
		window.o \
		gpio-sysfs.o \
		gz_clk.o \
		bcm2835.o \
		adcreader.o \
		Bessel.o \
		Biquad.o \
		Butterworth.o \
		Cascade.o \
		ChebyshevI.o \
		ChebyshevII.o \
		Custom.o \
		Elliptic.o \
		Legendre.o \
		PoleFilter.o \
		RBJ.o \
		RootFinder.o \
		State.o \
		moc_window.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		QwtExample.pro
QMAKE_TARGET  = QwtExample
DESTDIR       = 
TARGET        = QwtExample

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: QwtExample.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/arm-linux-gnueabihf/libQtGui.prl \
		/usr/lib/arm-linux-gnueabihf/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile QwtExample.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/arm-linux-gnueabihf/libQtGui.prl:
/usr/lib/arm-linux-gnueabihf/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile QwtExample.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/QwtExample1.0.0 || $(MKDIR) .tmp/QwtExample1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/QwtExample1.0.0/ && $(COPY_FILE) --parents window.h bcm2835.h gpio-sysfs.h gz_clk.h adcreader.h Iir.h iir/Bessel.h iir/Biquad.h iir/Butterworth.h iir/Cascade.h iir/ChebyshevI.h iir/ChebyshevII.h iir/Common.h iir/config.h iir/Custom.h iir/Elliptic.h iir/Layout.h iir/Legendre.h iir/MathSupplement.h iir/PoleFilter.h iir/RBJ.h iir/RootFinder.h iir/State.h iir/Types.h iir/Utilities.h .tmp/QwtExample1.0.0/ && $(COPY_FILE) --parents main.cpp window.cpp gpio-sysfs.cpp gz_clk.cpp bcm2835.c adcreader.cpp iir/Bessel.cpp iir/Biquad.cpp iir/Butterworth.cpp iir/Cascade.cpp iir/ChebyshevI.cpp iir/ChebyshevII.cpp iir/Custom.cpp iir/Elliptic.cpp iir/Legendre.cpp iir/PoleFilter.cpp iir/RBJ.cpp iir/RootFinder.cpp iir/State.cpp .tmp/QwtExample1.0.0/ && (cd `dirname .tmp/QwtExample1.0.0` && $(TAR) QwtExample1.0.0.tar QwtExample1.0.0 && $(COMPRESS) QwtExample1.0.0.tar) && $(MOVE) `dirname .tmp/QwtExample1.0.0`/QwtExample1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/QwtExample1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_window.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_window.cpp
moc_window.cpp: adcreader.h \
		gz_clk.h \
		bcm2835.h \
		gpio-sysfs.h \
		Iir.h \
		iir/Common.h \
		iir/Biquad.h \
		iir/MathSupplement.h \
		iir/Types.h \
		iir/Cascade.h \
		iir/Layout.h \
		iir/PoleFilter.h \
		iir/State.h \
		iir/Utilities.h \
		iir/Bessel.h \
		iir/RootFinder.h \
		iir/Butterworth.h \
		iir/ChebyshevI.h \
		iir/ChebyshevII.h \
		iir/Custom.h \
		iir/Elliptic.h \
		iir/Legendre.h \
		iir/RBJ.h \
		window.h
	/usr/lib/arm-linux-gnueabihf/qt4/bin/moc $(DEFINES) $(INCPATH) window.h -o moc_window.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp window.h \
		adcreader.h \
		gz_clk.h \
		bcm2835.h \
		gpio-sysfs.h \
		Iir.h \
		iir/Common.h \
		iir/Biquad.h \
		iir/MathSupplement.h \
		iir/Types.h \
		iir/Cascade.h \
		iir/Layout.h \
		iir/PoleFilter.h \
		iir/State.h \
		iir/Utilities.h \
		iir/Bessel.h \
		iir/RootFinder.h \
		iir/Butterworth.h \
		iir/ChebyshevI.h \
		iir/ChebyshevII.h \
		iir/Custom.h \
		iir/Elliptic.h \
		iir/Legendre.h \
		iir/RBJ.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

window.o: window.cpp window.h \
		adcreader.h \
		gz_clk.h \
		bcm2835.h \
		gpio-sysfs.h \
		Iir.h \
		iir/Common.h \
		iir/Biquad.h \
		iir/MathSupplement.h \
		iir/Types.h \
		iir/Cascade.h \
		iir/Layout.h \
		iir/PoleFilter.h \
		iir/State.h \
		iir/Utilities.h \
		iir/Bessel.h \
		iir/RootFinder.h \
		iir/Butterworth.h \
		iir/ChebyshevI.h \
		iir/ChebyshevII.h \
		iir/Custom.h \
		iir/Elliptic.h \
		iir/Legendre.h \
		iir/RBJ.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o window.o window.cpp

gpio-sysfs.o: gpio-sysfs.cpp gpio-sysfs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gpio-sysfs.o gpio-sysfs.cpp

gz_clk.o: gz_clk.cpp gz_clk.h \
		bcm2835.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gz_clk.o gz_clk.cpp

bcm2835.o: bcm2835.c bcm2835.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o bcm2835.o bcm2835.c

adcreader.o: adcreader.cpp adcreader.h \
		gz_clk.h \
		bcm2835.h \
		gpio-sysfs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o adcreader.o adcreader.cpp

Bessel.o: iir/Bessel.cpp iir/Common.h \
		iir/Bessel.h \
		iir/Cascade.h \
		iir/Biquad.h \
		iir/MathSupplement.h \
		iir/Types.h \
		iir/Layout.h \
		iir/PoleFilter.h \
		iir/State.h \
		iir/RootFinder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Bessel.o iir/Bessel.cpp

Biquad.o: iir/Biquad.cpp iir/Common.h \
		iir/MathSupplement.h \
		iir/Biquad.h \
		iir/Types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Biquad.o iir/Biquad.cpp

Butterworth.o: iir/Butterworth.cpp iir/Common.h \
		iir/Butterworth.h \
		iir/Cascade.h \
		iir/Biquad.h \
		iir/MathSupplement.h \
		iir/Types.h \
		iir/Layout.h \
		iir/PoleFilter.h \
		iir/State.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Butterworth.o iir/Butterworth.cpp

Cascade.o: iir/Cascade.cpp iir/Common.h \
		iir/Cascade.h \
		iir/Biquad.h \
		iir/MathSupplement.h \
		iir/Types.h \
		iir/Layout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Cascade.o iir/Cascade.cpp

ChebyshevI.o: iir/ChebyshevI.cpp iir/Common.h \
		iir/ChebyshevI.h \
		iir/Cascade.h \
		iir/Biquad.h \
		iir/MathSupplement.h \
		iir/Types.h \
		iir/Layout.h \
		iir/PoleFilter.h \
		iir/State.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ChebyshevI.o iir/ChebyshevI.cpp

ChebyshevII.o: iir/ChebyshevII.cpp iir/Common.h \
		iir/ChebyshevII.h \
		iir/Cascade.h \
		iir/Biquad.h \
		iir/MathSupplement.h \
		iir/Types.h \
		iir/Layout.h \
		iir/PoleFilter.h \
		iir/State.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ChebyshevII.o iir/ChebyshevII.cpp

Custom.o: iir/Custom.cpp iir/Common.h \
		iir/Custom.h \
		iir/Biquad.h \
		iir/MathSupplement.h \
		iir/Types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Custom.o iir/Custom.cpp

Elliptic.o: iir/Elliptic.cpp iir/Common.h \
		iir/Elliptic.h \
		iir/Cascade.h \
		iir/Biquad.h \
		iir/MathSupplement.h \
		iir/Types.h \
		iir/Layout.h \
		iir/PoleFilter.h \
		iir/State.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Elliptic.o iir/Elliptic.cpp

Legendre.o: iir/Legendre.cpp iir/Common.h \
		iir/Legendre.h \
		iir/Cascade.h \
		iir/Biquad.h \
		iir/MathSupplement.h \
		iir/Types.h \
		iir/Layout.h \
		iir/PoleFilter.h \
		iir/State.h \
		iir/RootFinder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Legendre.o iir/Legendre.cpp

PoleFilter.o: iir/PoleFilter.cpp iir/Common.h \
		iir/PoleFilter.h \
		iir/MathSupplement.h \
		iir/Cascade.h \
		iir/Biquad.h \
		iir/Types.h \
		iir/Layout.h \
		iir/State.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PoleFilter.o iir/PoleFilter.cpp

RBJ.o: iir/RBJ.cpp iir/Common.h \
		iir/RBJ.h \
		iir/Biquad.h \
		iir/MathSupplement.h \
		iir/Types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RBJ.o iir/RBJ.cpp

RootFinder.o: iir/RootFinder.cpp iir/Common.h \
		iir/RootFinder.h \
		iir/Types.h \
		iir/MathSupplement.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RootFinder.o iir/RootFinder.cpp

State.o: iir/State.cpp iir/Common.h \
		iir/State.h \
		iir/Biquad.h \
		iir/MathSupplement.h \
		iir/Types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o State.o iir/State.cpp

moc_window.o: moc_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_window.o moc_window.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

