#############################################################################
# Makefile for building: QwtExample
# Generated by qmake (3.0) (Qt 5.3.2)
# Project:  QwtExample.pro
# Template: app
# Command: /usr/lib/arm-linux-gnueabihf/qt5/bin/qmake -o Makefile QwtExample.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -I. -I/usr/local/qwt-6.1.2/include -isystem /usr/include/arm-linux-gnueabihf/qt5 -isystem /usr/include/arm-linux-gnueabihf/qt5/QtWidgets -isystem /usr/include/arm-linux-gnueabihf/qt5/QtGui -isystem /usr/include/arm-linux-gnueabihf/qt5/QtCore -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -lm -L/usr/local/qwt-6.1.2/lib -lqwt -lQt5Widgets -lQt5Gui -lQt5Core -lGLESv2 -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/arm-linux-gnueabihf/qt5/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		window.cpp \
		gpio-sysfs.cpp \
		gz_clk.cpp \
		bcm2835.c \
		adcreader.cpp \
		iir/Bessel.cpp \
		iir/Biquad.cpp \
		iir/Butterworth.cpp \
		iir/Cascade.cpp \
		iir/ChebyshevI.cpp \
		iir/ChebyshevII.cpp \
		iir/Custom.cpp \
		iir/Elliptic.cpp \
		iir/Legendre.cpp \
		iir/PoleFilter.cpp \
		iir/RBJ.cpp \
		iir/RootFinder.cpp \
		iir/State.cpp moc_window.cpp
OBJECTS       = main.o \
		window.o \
		gpio-sysfs.o \
		gz_clk.o \
		bcm2835.o \
		adcreader.o \
		Bessel.o \
		Biquad.o \
		Butterworth.o \
		Cascade.o \
		ChebyshevI.o \
		ChebyshevII.o \
		Custom.o \
		Elliptic.o \
		Legendre.o \
		PoleFilter.o \
		RBJ.o \
		RootFinder.o \
		State.o \
		moc_window.o
DIST          = /usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/unix.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/linux.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/qconfig.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/default_post.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/resources.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/moc.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/uic.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/yacc.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/lex.prf \
		QwtExample.pro main.cpp \
		window.cpp \
		gpio-sysfs.cpp \
		gz_clk.cpp \
		bcm2835.c \
		adcreader.cpp \
		iir/Bessel.cpp \
		iir/Biquad.cpp \
		iir/Butterworth.cpp \
		iir/Cascade.cpp \
		iir/ChebyshevI.cpp \
		iir/ChebyshevII.cpp \
		iir/Custom.cpp \
		iir/Elliptic.cpp \
		iir/Legendre.cpp \
		iir/PoleFilter.cpp \
		iir/RBJ.cpp \
		iir/RootFinder.cpp \
		iir/State.cpp
QMAKE_TARGET  = QwtExample
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = QwtExample


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: QwtExample.pro /usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/unix.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/linux.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/qconfig.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/default_post.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/resources.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/moc.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/uic.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/yacc.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/lex.prf \
		QwtExample.pro \
		/usr/lib/arm-linux-gnueabihf/libQt5Widgets.prl \
		/usr/lib/arm-linux-gnueabihf/libQt5Gui.prl \
		/usr/lib/arm-linux-gnueabihf/libQt5Core.prl
	$(QMAKE) -o Makefile QwtExample.pro
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/shell-unix.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/unix.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/linux.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/g++-base.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/qconfig.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt_config.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/spec_post.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/default_pre.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/default_post.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/warn_on.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/resources.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/moc.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/uic.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/exceptions.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/yacc.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/lex.prf:
QwtExample.pro:
/usr/lib/arm-linux-gnueabihf/libQt5Widgets.prl:
/usr/lib/arm-linux-gnueabihf/libQt5Gui.prl:
/usr/lib/arm-linux-gnueabihf/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile QwtExample.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/QwtExample1.0.0 || mkdir -p .tmp/QwtExample1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/QwtExample1.0.0/ && $(COPY_FILE) --parents window.h bcm2835.h gpio-sysfs.h gz_clk.h adcreader.h Iir.h iir/Bessel.h iir/Biquad.h iir/Butterworth.h iir/Cascade.h iir/ChebyshevI.h iir/ChebyshevII.h iir/Common.h iir/config.h iir/Custom.h iir/Elliptic.h iir/Layout.h iir/Legendre.h iir/MathSupplement.h iir/PoleFilter.h iir/RBJ.h iir/RootFinder.h iir/State.h iir/Types.h iir/Utilities.h .tmp/QwtExample1.0.0/ && $(COPY_FILE) --parents main.cpp window.cpp gpio-sysfs.cpp gz_clk.cpp bcm2835.c adcreader.cpp iir/Bessel.cpp iir/Biquad.cpp iir/Butterworth.cpp iir/Cascade.cpp iir/ChebyshevI.cpp iir/ChebyshevII.cpp iir/Custom.cpp iir/Elliptic.cpp iir/Legendre.cpp iir/PoleFilter.cpp iir/RBJ.cpp iir/RootFinder.cpp iir/State.cpp .tmp/QwtExample1.0.0/ && (cd `dirname .tmp/QwtExample1.0.0` && $(TAR) QwtExample1.0.0.tar QwtExample1.0.0 && $(COMPRESS) QwtExample1.0.0.tar) && $(MOVE) `dirname .tmp/QwtExample1.0.0`/QwtExample1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/QwtExample1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_window.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_window.cpp
moc_window.cpp: /usr/local/qwt-6.1.2/include/qwt_thermo.h \
		/usr/local/qwt-6.1.2/include/qwt_global.h \
		/usr/local/qwt-6.1.2/include/qwt_abstract_scale.h \
		/usr/local/qwt-6.1.2/include/qwt_interval.h \
		/usr/local/qwt-6.1.2/include/qwt_knob.h \
		/usr/local/qwt-6.1.2/include/qwt_abstract_slider.h \
		/usr/local/qwt-6.1.2/include/qwt_plot.h \
		/usr/local/qwt-6.1.2/include/qwt_text.h \
		/usr/local/qwt-6.1.2/include/qwt_plot_dict.h \
		/usr/local/qwt-6.1.2/include/qwt_plot_item.h \
		/usr/local/qwt-6.1.2/include/qwt_legend_data.h \
		/usr/local/qwt-6.1.2/include/qwt_graphic.h \
		/usr/local/qwt-6.1.2/include/qwt_null_paintdevice.h \
		/usr/local/qwt-6.1.2/include/qwt_scale_map.h \
		/usr/local/qwt-6.1.2/include/qwt_transform.h \
		/usr/local/qwt-6.1.2/include/qwt_plot_curve.h \
		/usr/local/qwt-6.1.2/include/qwt_plot_seriesitem.h \
		/usr/local/qwt-6.1.2/include/qwt_scale_div.h \
		/usr/local/qwt-6.1.2/include/qwt_series_data.h \
		/usr/local/qwt-6.1.2/include/qwt_samples.h \
		/usr/local/qwt-6.1.2/include/qwt_point_3d.h \
		/usr/local/qwt-6.1.2/include/qwt_point_polar.h \
		/usr/local/qwt-6.1.2/include/qwt_math.h \
		/usr/local/qwt-6.1.2/include/qwt_series_store.h \
		adcreader.h \
		gz_clk.h \
		bcm2835.h \
		gpio-sysfs.h \
		Iir.h \
		iir/Common.h \
		iir/Biquad.h \
		iir/MathSupplement.h \
		iir/Types.h \
		iir/Cascade.h \
		iir/Layout.h \
		iir/PoleFilter.h \
		iir/State.h \
		iir/Utilities.h \
		iir/Bessel.h \
		iir/RootFinder.h \
		iir/Butterworth.h \
		iir/ChebyshevI.h \
		iir/ChebyshevII.h \
		iir/Custom.h \
		iir/Elliptic.h \
		iir/Legendre.h \
		iir/RBJ.h \
		window.h
	/usr/lib/arm-linux-gnueabihf/qt5/bin/moc $(DEFINES) -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -I/home/pi/Team4_ECG -I/usr/local/qwt-6.1.2/include -I/usr/include/arm-linux-gnueabihf/qt5 -I/usr/include/arm-linux-gnueabihf/qt5/QtWidgets -I/usr/include/arm-linux-gnueabihf/qt5/QtGui -I/usr/include/arm-linux-gnueabihf/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/arm-linux-gnueabihf/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/arm-linux-gnueabihf/4.9/include -I/usr/local/include -I/usr/lib/gcc/arm-linux-gnueabihf/4.9/include-fixed -I/usr/include/arm-linux-gnueabihf -I/usr/include window.h -o moc_window.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp window.h \
		/usr/local/qwt-6.1.2/include/qwt_thermo.h \
		/usr/local/qwt-6.1.2/include/qwt_global.h \
		/usr/local/qwt-6.1.2/include/qwt_abstract_scale.h \
		/usr/local/qwt-6.1.2/include/qwt_interval.h \
		/usr/local/qwt-6.1.2/include/qwt_knob.h \
		/usr/local/qwt-6.1.2/include/qwt_abstract_slider.h \
		/usr/local/qwt-6.1.2/include/qwt_plot.h \
		/usr/local/qwt-6.1.2/include/qwt_text.h \
		/usr/local/qwt-6.1.2/include/qwt_plot_dict.h \
		/usr/local/qwt-6.1.2/include/qwt_plot_item.h \
		/usr/local/qwt-6.1.2/include/qwt_legend_data.h \
		/usr/local/qwt-6.1.2/include/qwt_graphic.h \
		/usr/local/qwt-6.1.2/include/qwt_null_paintdevice.h \
		/usr/local/qwt-6.1.2/include/qwt_scale_map.h \
		/usr/local/qwt-6.1.2/include/qwt_transform.h \
		/usr/local/qwt-6.1.2/include/qwt_plot_curve.h \
		/usr/local/qwt-6.1.2/include/qwt_plot_seriesitem.h \
		/usr/local/qwt-6.1.2/include/qwt_scale_div.h \
		/usr/local/qwt-6.1.2/include/qwt_series_data.h \
		/usr/local/qwt-6.1.2/include/qwt_samples.h \
		/usr/local/qwt-6.1.2/include/qwt_point_3d.h \
		/usr/local/qwt-6.1.2/include/qwt_point_polar.h \
		/usr/local/qwt-6.1.2/include/qwt_math.h \
		/usr/local/qwt-6.1.2/include/qwt_series_store.h \
		adcreader.h \
		gz_clk.h \
		bcm2835.h \
		gpio-sysfs.h \
		Iir.h \
		iir/Common.h \
		iir/Biquad.h \
		iir/MathSupplement.h \
		iir/Types.h \
		iir/Cascade.h \
		iir/Layout.h \
		iir/PoleFilter.h \
		iir/State.h \
		iir/Utilities.h \
		iir/Bessel.h \
		iir/RootFinder.h \
		iir/Butterworth.h \
		iir/ChebyshevI.h \
		iir/ChebyshevII.h \
		iir/Custom.h \
		iir/Elliptic.h \
		iir/Legendre.h \
		iir/RBJ.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

window.o: window.cpp window.h \
		/usr/local/qwt-6.1.2/include/qwt_thermo.h \
		/usr/local/qwt-6.1.2/include/qwt_global.h \
		/usr/local/qwt-6.1.2/include/qwt_abstract_scale.h \
		/usr/local/qwt-6.1.2/include/qwt_interval.h \
		/usr/local/qwt-6.1.2/include/qwt_knob.h \
		/usr/local/qwt-6.1.2/include/qwt_abstract_slider.h \
		/usr/local/qwt-6.1.2/include/qwt_plot.h \
		/usr/local/qwt-6.1.2/include/qwt_text.h \
		/usr/local/qwt-6.1.2/include/qwt_plot_dict.h \
		/usr/local/qwt-6.1.2/include/qwt_plot_item.h \
		/usr/local/qwt-6.1.2/include/qwt_legend_data.h \
		/usr/local/qwt-6.1.2/include/qwt_graphic.h \
		/usr/local/qwt-6.1.2/include/qwt_null_paintdevice.h \
		/usr/local/qwt-6.1.2/include/qwt_scale_map.h \
		/usr/local/qwt-6.1.2/include/qwt_transform.h \
		/usr/local/qwt-6.1.2/include/qwt_plot_curve.h \
		/usr/local/qwt-6.1.2/include/qwt_plot_seriesitem.h \
		/usr/local/qwt-6.1.2/include/qwt_scale_div.h \
		/usr/local/qwt-6.1.2/include/qwt_series_data.h \
		/usr/local/qwt-6.1.2/include/qwt_samples.h \
		/usr/local/qwt-6.1.2/include/qwt_point_3d.h \
		/usr/local/qwt-6.1.2/include/qwt_point_polar.h \
		/usr/local/qwt-6.1.2/include/qwt_math.h \
		/usr/local/qwt-6.1.2/include/qwt_series_store.h \
		adcreader.h \
		gz_clk.h \
		bcm2835.h \
		gpio-sysfs.h \
		Iir.h \
		iir/Common.h \
		iir/Biquad.h \
		iir/MathSupplement.h \
		iir/Types.h \
		iir/Cascade.h \
		iir/Layout.h \
		iir/PoleFilter.h \
		iir/State.h \
		iir/Utilities.h \
		iir/Bessel.h \
		iir/RootFinder.h \
		iir/Butterworth.h \
		iir/ChebyshevI.h \
		iir/ChebyshevII.h \
		iir/Custom.h \
		iir/Elliptic.h \
		iir/Legendre.h \
		iir/RBJ.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o window.o window.cpp

gpio-sysfs.o: gpio-sysfs.cpp gpio-sysfs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gpio-sysfs.o gpio-sysfs.cpp

gz_clk.o: gz_clk.cpp gz_clk.h \
		bcm2835.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gz_clk.o gz_clk.cpp

bcm2835.o: bcm2835.c bcm2835.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o bcm2835.o bcm2835.c

adcreader.o: adcreader.cpp adcreader.h \
		gz_clk.h \
		bcm2835.h \
		gpio-sysfs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o adcreader.o adcreader.cpp

Bessel.o: iir/Bessel.cpp iir/Common.h \
		iir/Bessel.h \
		iir/Cascade.h \
		iir/Biquad.h \
		iir/MathSupplement.h \
		iir/Types.h \
		iir/Layout.h \
		iir/PoleFilter.h \
		iir/State.h \
		iir/RootFinder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Bessel.o iir/Bessel.cpp

Biquad.o: iir/Biquad.cpp iir/Common.h \
		iir/MathSupplement.h \
		iir/Biquad.h \
		iir/Types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Biquad.o iir/Biquad.cpp

Butterworth.o: iir/Butterworth.cpp iir/Common.h \
		iir/Butterworth.h \
		iir/Cascade.h \
		iir/Biquad.h \
		iir/MathSupplement.h \
		iir/Types.h \
		iir/Layout.h \
		iir/PoleFilter.h \
		iir/State.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Butterworth.o iir/Butterworth.cpp

Cascade.o: iir/Cascade.cpp iir/Common.h \
		iir/Cascade.h \
		iir/Biquad.h \
		iir/MathSupplement.h \
		iir/Types.h \
		iir/Layout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Cascade.o iir/Cascade.cpp

ChebyshevI.o: iir/ChebyshevI.cpp iir/Common.h \
		iir/ChebyshevI.h \
		iir/Cascade.h \
		iir/Biquad.h \
		iir/MathSupplement.h \
		iir/Types.h \
		iir/Layout.h \
		iir/PoleFilter.h \
		iir/State.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ChebyshevI.o iir/ChebyshevI.cpp

ChebyshevII.o: iir/ChebyshevII.cpp iir/Common.h \
		iir/ChebyshevII.h \
		iir/Cascade.h \
		iir/Biquad.h \
		iir/MathSupplement.h \
		iir/Types.h \
		iir/Layout.h \
		iir/PoleFilter.h \
		iir/State.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ChebyshevII.o iir/ChebyshevII.cpp

Custom.o: iir/Custom.cpp iir/Common.h \
		iir/Custom.h \
		iir/Biquad.h \
		iir/MathSupplement.h \
		iir/Types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Custom.o iir/Custom.cpp

Elliptic.o: iir/Elliptic.cpp iir/Common.h \
		iir/Elliptic.h \
		iir/Cascade.h \
		iir/Biquad.h \
		iir/MathSupplement.h \
		iir/Types.h \
		iir/Layout.h \
		iir/PoleFilter.h \
		iir/State.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Elliptic.o iir/Elliptic.cpp

Legendre.o: iir/Legendre.cpp iir/Common.h \
		iir/Legendre.h \
		iir/Cascade.h \
		iir/Biquad.h \
		iir/MathSupplement.h \
		iir/Types.h \
		iir/Layout.h \
		iir/PoleFilter.h \
		iir/State.h \
		iir/RootFinder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Legendre.o iir/Legendre.cpp

PoleFilter.o: iir/PoleFilter.cpp iir/Common.h \
		iir/PoleFilter.h \
		iir/MathSupplement.h \
		iir/Cascade.h \
		iir/Biquad.h \
		iir/Types.h \
		iir/Layout.h \
		iir/State.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PoleFilter.o iir/PoleFilter.cpp

RBJ.o: iir/RBJ.cpp iir/Common.h \
		iir/RBJ.h \
		iir/Biquad.h \
		iir/MathSupplement.h \
		iir/Types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RBJ.o iir/RBJ.cpp

RootFinder.o: iir/RootFinder.cpp iir/Common.h \
		iir/RootFinder.h \
		iir/Types.h \
		iir/MathSupplement.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RootFinder.o iir/RootFinder.cpp

State.o: iir/State.cpp iir/Common.h \
		iir/State.h \
		iir/Biquad.h \
		iir/MathSupplement.h \
		iir/Types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o State.o iir/State.cpp

moc_window.o: moc_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_window.o moc_window.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

